export const INITIAL_TRIPS = [
    {
        id: 1,
        title: "Tokyo Explorer",
        flag: "🗼",
        destination: "Tokyo & Kyoto",
        region: "Japan · Asia",
        dates: "Sep 3 – 8, 2025",
        days: 5,
        travelers: 2,
        stops: 23,
        budget: "$4.4k",
        status: "ongoing",
        coverColor: "#E6F1FB",
    },
    {
        id: 2,
        title: "Amalfi Coast Road Trip",
        flag: "🍋",
        destination: "Naples, Positano, Ravello",
        region: "Italy · Europe",
        dates: "Oct 12 – 20, 2025",
        days: 8,
        travelers: 2,
        stops: 18,
        budget: "$3.2k",
        status: "upcoming",
        coverColor: "#FAEEDA",
    },
    {
        id: 3,
        title: "Morocco Desert Adventure",
        flag: "🐪",
        destination: "Marrakech, Fes, Sahara",
        region: "Morocco · Africa",
        dates: "Nov 5 – 14, 2025",
        days: 9,
        travelers: 3,
        stops: 21,
        budget: "$2.8k",
        status: "planning",
        coverColor: "#FAECE7",
    },
    {
        id: 4,
        title: "New York City Long Weekend",
        flag: "🗽",
        destination: "Manhattan, Brooklyn",
        region: "USA · North America",
        dates: "Dec 19 – 22, 2025",
        days: 3,
        travelers: 2,
        stops: 12,
        budget: "$1.6k",
        status: "planning",
        coverColor: "#EEEDFE",
    },
    {
        id: 5,
        title: "Patagonia Trek",
        flag: "🏔",
        destination: "Torres del Paine, El Chaltén",
        region: "Chile & Argentina · South America",
        dates: "Jan 10 – 24, 2026",
        days: 14,
        travelers: 2,
        stops: 16,
        budget: "$5.1k",
        status: "planning",
        coverColor: "#E1F5EE",
    },
    {
        id: 6,
        title: "Paris Spring Escape",
        flag: "🗼",
        destination: "Paris, Versailles",
        region: "France · Europe",
        dates: "Jul 12 – 19, 2025",
        days: 7,
        travelers: 2,
        stops: 19,
        budget: "$3.8k",
        status: "completed",
        coverColor: "#FBEAF0",
    },
    {
        id: 7,
        title: "Bali & Lombok",
        flag: "🌴",
        destination: "Ubud, Seminyak, Lombok",
        region: "Indonesia · Asia",
        dates: "Apr 2 – 15, 2025",
        days: 13,
        travelers: 2,
        stops: 24,
        budget: "$2.4k",
        status: "completed",
        coverColor: "#EAF3DE",
    },
];