export const INITIAL_TRIPS = [
    {
        id: 1,
        title: "Tokyo Explorer",
        flag: "🗼",
        destination: "Tokyo & Kyoto",
        region: "Japan · Asia",
        dates: "Sep 3 – 8, 2025",
        days: 5,
        travelers: 2,
        stops: 23,
        budget: "$4.4k",
        status: "ongoing",
        coverColor: "#E6F1FB",
    },
    {
        id: 2,
        title: "Amalfi Coast Road Trip",
        flag: "🍋",
        destination: "Naples, Positano, Ravello",
        region: "Italy · Europe",
        dates: "Oct 12 – 20, 2025",
        days: 8,
        travelers: 2,
        stops: 18,
        budget: "$3.2k",
        status: "upcoming",
        coverColor: "#FAEEDA",
    },
    {
        id: 3,
        title: "Morocco Desert Adventure",
        flag: "🐪",
        destination: "Marrakech, Fes, Sahara",
        region: "Morocco · Africa",
        dates: "Nov 5 – 14, 2025",
        days: 9,
        travelers: 3,
        stops: 21,
        budget: "$2.8k",
        status: "planning",
        coverColor: "#FAECE7",
    },
    {
        id: 4,
        title: "New York City Long Weekend",
        flag: "🗽",
        destination: "Manhattan, Brooklyn",
        region: "USA · North America",
        dates: "Dec 19 – 22, 2025",
        days: 3,
        travelers: 2,
        stops: 12,
        budget: "$1.6k",
        status: "planning",
        coverColor: "#EEEDFE",
    },
    {
        id: 5,
        title: "Patagonia Trek",
        flag: "🏔",
        destination: "Torres del Paine, El Chaltén",
        region: "Chile & Argentina · South America",
        dates: "Jan 10 – 24, 2026",
        days: 14,
        travelers: 2,
        stops: 16,
        budget: "$5.1k",
        status: "planning",
        coverColor: "#E1F5EE",
    },
    {
        id: 6,
        title: "Paris Spring Escape",
        flag: "🗼",
        destination: "Paris, Versailles",
        region: "France · Europe",
        dates: "Jul 12 – 19, 2025",
        days: 7,
        travelers: 2,
        stops: 19,
        budget: "$3.8k",
        status: "completed",
        coverColor: "#FBEAF0",
    },
    {
        id: 7,
        title: "Bali & Lombok",
        flag: "🌴",
        destination: "Ubud, Seminyak, Lombok",
        region: "Indonesia · Asia",
        dates: "Apr 2 – 15, 2025",
        days: 13,
        travelers: 2,
        stops: 24,
        budget: "$2.4k",
        status: "completed",
        coverColor: "#EAF3DE",
    },
]; 

export const INITIAL_CHECKLIST = [
  // Documents
  { id: 1,  category: "Documents",   text: "Passport (valid 6+ months)",          checked: false },
  { id: 2,  category: "Documents",   text: "Travel insurance card / PDF",          checked: false },
  { id: 3,  category: "Documents",   text: "Flight e-tickets printed / saved",     checked: false },
  { id: 4,  category: "Documents",   text: "Hotel confirmations",                  checked: false },
  { id: 5,  category: "Documents",   text: "Emergency contact list",               checked: false },
  // Money
  { id: 6,  category: "Money",       text: "Local cash (¥30,000 for arrival)",     checked: false },
  { id: 7,  category: "Money",       text: "Notify bank of travel dates",          checked: false },
  { id: 8,  category: "Money",       text: "Credit card with no FX fee",           checked: false },
  // Connectivity
  { id: 9,  category: "Connectivity","text": "Pocket WiFi pre-ordered",            checked: false },
  { id: 10, category: "Connectivity","text": "Download offline maps (Google Maps)", checked: false },
  { id: 11, category: "Connectivity","text": "Google Translate — Japanese offline", checked: false },
  // Clothing
  { id: 12, category: "Clothing",    text: "Slip-on shoes (temples require removal)", checked: false },
  { id: 13, category: "Clothing",    text: "Light layers for shrine hikes",        checked: false },
  { id: 14, category: "Clothing",    text: "Compact umbrella",                     checked: false },
  // Health
  { id: 15, category: "Health",      text: "Prescription medication + copy",       checked: false },
  { id: 16, category: "Health",      text: "Basic first-aid kit",                  checked: false },
  // Activities
  { id: 17, category: "Activities",  text: "teamLab Borderless tickets",           checked: false },
  { id: 18, category: "Activities",  text: "Shinkansen reserved seat tickets",     checked: false },
  { id: 19, category: "Activities",  text: "Omakase restaurant reservations",      checked: false },
];
 
export const INITIAL_NOTES = [
  { id: 1, title: "Restaurant wish list", body: "- Tempura Kondo (Ginza)\n- Narisawa (modern Japanese)\n- Afuri ramen (yuzu shio)\n- Tsuta (Michelin ramen, Sugamo)\n- Standing sushi bar in Tsukiji" },
  { id: 2, title: "Souvenir ideas", body: "- Matcha KitKats from convenience store\n- Tenugui hand towels (Asakusa)\n- Sake from Isetan basement\n- Ceramic chopstick rests\n- Daruma doll from Senso-ji" },
  { id: 3, title: "Phrases to remember", body: "Sumimasen = Excuse me / Sorry\nArigato gozaimasu = Thank you very much\nEigo hanasemasu ka? = Do you speak English?\nKore wa ikura desu ka? = How much is this?\nOkaikei onegaishimasu = Bill please" },
];